# Generated by Django 5.2.7 on 2025-10-31 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videoapp', '0003_paymentcard'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meeting',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
