# Generated by Django 5.2.7 on 2025-10-31 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videoapp', '0004_alter_meeting_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='plan',
            field=models.CharField(default='unknown', max_length=50),
        ),
    ]
