# Generated by Django 4.2.7 on 2025-01-06 12:41

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('videoapp', '0004_meeting_host_meeting_users_room_channel_room_users_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='users',
        ),
        migrations.AddField(
            model_name='room',
            name='users',
            field=models.ManyToManyField(blank=True, null=True, related_name='rooms', to=settings.AUTH_USER_MODEL),
        ),
    ]
