# Generated by Django 5.2.7 on 2025-10-31 19:28

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videoapp', '0005_alter_subscription_plan'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='paymentcard',
            constraint=models.UniqueConstraint(fields=('card_number', 'expiry_date', 'cvv'), name='unique_card_triplet'),
        ),
    ]
