# Generated by Django 4.2.7 on 2025-01-08 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videoapp', '0006_rooms_delete_room'),
    ]

    operations = [
        migrations.CreateModel(
            name='Messageschat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifiant', models.IntegerField(blank=True, null=True)),
                ('text', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
    ]
