# Generated by Django 5.2.7 on 2025-10-31 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videoapp', '0006_paymentcard_unique_card_triplet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discussion',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
