# Generated by Django 4.2.7 on 2025-01-30 22:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('videoapp', '0007_messageschat'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chatmessages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('messages', models.JSONField(default=dict)),
                ('channel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='videoapp.meeting')),
            ],
        ),
    ]
