# Generated by Django 4.2.7 on 2025-01-30 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videoapp', '0008_chatmessages'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatmessages',
            name='messages',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
