# Generated by Django 4.2.7 on 2025-01-30 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videoapp', '0009_alter_chatmessages_messages'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessages',
            name='messages_chat',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
