# Generated by Django 5.1.5 on 2025-02-09 16:27

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videoapp', '0011_activeuser'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activeuser',
            name='user',
        ),
        migrations.AddField(
            model_name='activeuser',
            name='user',
            field=models.ManyToManyField(blank=True, null=True, related_name='active_users', to=settings.AUTH_USER_MODEL),
        ),
    ]
