# Generated by Django 5.1.5 on 2025-02-11 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videoapp', '0013_discussion_discussionmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='discussionmessage',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='uploads/'),
        ),
        migrations.AlterField(
            model_name='discussionmessage',
            name='content',
            field=models.TextField(blank=True, null=True),
        ),
    ]
